import '../globals.css';
import type { Metadata } from 'next';
import { Archivo } from 'next/font/google';
import Footer from '@/components/Footer';
import { ContextProvider } from '@/context';
import { Toaster } from '@/components/ui/sonner';

const archivo = Archivo({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${archivo.className} antialiased scroll-smooth flex justify-between flex-col min-h-screen relative`}>
        <Toaster />
        <ContextProvider>{children}</ContextProvider>
        <Footer />
      </body>
    </html>
  );
}
