import '../globals.css';
import type { Metadata } from 'next';
import { Archivo } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';

const archivo = Archivo({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${archivo.className} antialiased flex justify-center items-center min-h-screen md:bg-gray-100`}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
