import '../globals.css';
import type { Metadata } from 'next';
import { Archivo } from 'next/font/google';
import { Toaster } from '@/components/ui/sonner';
import { SidebarProvider } from '@/components/ui/sidebar';
import AdminSidebar from '@/components/admin/AdminSidebar';
import { AdminNavbar } from '@/components/admin/AdminNavbar';
import { ContextProvider } from '@/context';

const archivo = Archivo({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${archivo.className} antialiased flex justify-center items-center min-h-screen md:bg-gray-100`}>
        <Toaster />
        <ContextProvider>
          <SidebarProvider>
            <AdminSidebar />
            <main className='flex-1 flex flex-col justify-between min-h-screen overflow-x-hidden'>
              <AdminNavbar />
              {children}
            </main>
          </SidebarProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
